### ISSUE TITLE
基于 JSBox 对大内存模式的移除, 是不是可以考虑买 Pin 了

### ISSUE THREAD

**Issue by ghost** [coo11/pinplus#8]
- 基于 JSBox 对大内存模式的移除, 是不是可以考虑买 Pin 了(当初没有买 JSBox 和 Pin 的组合就是嫌 Pin 没有 JSBox 简洁和自定义程度高, 而现在 Pin 也没有采取订阅制😥)

**Comment by coo11** [comment]
要是对剪贴板的使用非常有需求的话可以考虑。
但个人不推荐，毕竟通知中心在 iOS14 上已经式微了，实在不行尝试一下 Taio，要是适应了其实还好。

**Comment by ghost** [comment]
> Taio

- 谢谢，Taio 的界面对文本处理比较好
- 能不能写一个类似 Taio 保存剪切板的 Widget 的 JSBox 脚本 🧐

**Comment by coo11** [comment]
个人没什么需求，而且桌面 Widget 太鸡肋了。
